### ISSUE TITLE
Studio Registration error

### ISSUE THREAD

**Issue by jtmuller5** [tablelandnetwork/site-tableland#167]
I am unable to sign in to the Studio after connecting my wallet:

![image](https://github.com/tablelandnetwork/site-tableland/assets/47997351/56945593-feb7-4b68-9c41-8f154708dcb6)

**Comment by joewagner** [comment]
Hey @jtmuller5 thanks for the report.  We are looking into the issue now. 
When did this happen?

**Comment by jtmuller5** [comment]
Just now. I learned about Tableland through a hackathon and wanted to give it a try.

**Comment by joewagner** [comment]
Can you try to create an account again? if it fails it would be great to know some details:
- what browser?
- what OS?
- what wallet?
- any errors in the browser console?

Thank you again for the report!

**Comment by joewagner** [comment]
I was able to reproduce the issue, no need to retry.  We will work on fixing asap.

**Comment by jtmuller5** [comment]
Awesome!

Here was the error from my browser console:

```
[
    {
        "error": {
            "json": {
                "message": "BATCH_ERROR: This operation was aborted",
                "code": -32603,
                "data": {
                    "code": "INTERNAL_SERVER_ERROR",
                    "httpStatus": 500,
                    "path": "auth.register",
                    "zodError": null
                }
            }
        }
    }
]
```

**Comment by joewagner** [comment]
@jtmuller5 We found the issue, and deployed a fix.
Your account should exist, can you try to login again now?

**Comment by jtmuller5** [comment]
Thank you, I am logged in now ✅
